<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="detail-history-of-ayya-vaikundar.aspx.cs" Inherits="detail_history_of_ayya_vaikundar" Title="Detail History of Ayya Vaikundar-English" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
<title>Ayya Vaikundar - Detail History of Ayya Vaikundar</title>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
<div style="padding:10px;"><h1>History of Ayya Vaikundar</h1></div>
<div class="space"></div>
<div class="right"><a href="detail-history-of-ayya-vaikundar-in-tamil.aspx"> தமிழில் வாசிக்க</a></div>
<div class="space"></div>
<div style="padding:5px;">
<b><center style="font-size:25px;color:Maroon;">AYYA THUNAI</center></b>
<br />
<b><center style="font-size:18px;color:#0000ee;">HISTORY OF LORD NARAYANA’S INCARNATE LORD VAIKUNDAR</center></b>
<br /><br />
<center><img src="Images/thamarai.png" /></center>
<br /><br />
<center>‘Lord Narayana himself incarnated as Vaikundar’</center>
<br /><br />
<center><img src="Images/vaikudar.png" /></center>
<br /><br />
<b><center style="font-size:16px;color:Maroon;">SOURCE: AKILATHIRATTU</center></b>
<br /><br />
<span style="font-size:16px;color:Maroon;">Lord Vaikunda Swamy (C.1833 – C.1851):</span> According to the sacred book Akilathirattu which is comparable to the texts of Vedas, Lord Maha Vishnu, the creator and protector of the Universe, after ending Lord Krishna Avatar (incarnation), again himself incarnated as Lord Vaikundar which was the tenth manifestation in Kali Yuga as prophesied by Veda Vyasa in Adi Agama (Vedas).  While Veda agama Akilathirattu, reverently mentioned him as <b>Shri Pandaram, Aandavar, Shri Mayon, Shri Narayana, Lord Vishnu, Lord Thirumal, Shri Perumal, Ayya Narayana, Shri Sivanarayana and Shri Suryanarayana,</b> the devotees reverently worship him in the names of <b>‘Ayya’, ‘Lord Vaikunda Swami’ and ‘Lord Narayana Swami’</b>.
<br /><br />
The divine philosophy has been that whenever Adharma raised its ugly head, and threatened to destroy basic fabrics of Dharma, God, mainly Lord Maha Vishnu incarnated in some form of human and destroyed Adharma to re-establish the rule of Dharma. True to this philosophy, Lord Maha Vishnu’s incarnation as Lord Vaikundar in Kaliyuga, was meant to end the suffering and humiliation of mankind by destroying evil Kali and re-establish rule of law called Dharma. The glories of Lord Vaikundar, who incarnated to destroy evil Kali has been elegantly eulogized in the form of verses in Tamil in the sacred religious scripture Holy Akilathirattu, which contain the divine acts and doctrines of Lord Vaikundar as penned by Shri Arigopalan Citar. The sacred Akilathirattu is considered to be one of the sacred Veda Agama texts, similar to the ancient Veda texts written by Maharishi Veda Vyasa. It has been written as verses in the form of poem consisting of more than 15000 words. The original Akilathirattu has been reportedly recorded on palm leaves until it was printed in book form. The entire contents according to him have been penned by him as dictated by Lord Vaikundar in his dream on the 27th day of the Tamil Month Karthigai in the year Kollam which was 1016, corresponding to Friday, the 10th December 1841 CE. The place where this sacred text has been written by Shri Arigopalan Citar is called ‘Thenthamaraikulam Pathi’ 
<br /><br />
The Holy Akilathirattu narrates the origin and evolution of the universe, time line of the evolutionary history covering major events, and subsequent developments which shaped our land over billions of years, after the cosmic had been created. Holy Akilathirattu explains various incarnations of Lord Maha Vishnu who finally incarnated in Kaliyuga as Lord Vaikundar and prophecy for the future.
<br /><br />
<div style="padding-left:50px;">
    “Innal Vivaramellaam eduththu viyaagarum <br />
munnaal mozhintha murainoolpadiyaale<br />
naaraayanarum vanthu nadaththum valamaithannai<br />
kaaranamaa ezhuthik kathaiyaai padiththoarkku<br />
oyyaaramaaga ul vinainoi theerumendru<br />
ayaavumikkathaiyai arulgindranpore” - Akilathirattu  

</div>
<br /><br />
<span style="font-size:16px;color:Maroon;">Past Incarnations of Lord Mahavishnu:</span> According to the Veda agama Akilathirattu, God who is omnipresent and pervades in the universe is one and the same though they may appear in different forms such as Lord Shiva, Goddess Shakthi, Lord Omkara, Lord Vishnu, Lord Rudra, and Lord Maheshwar etc.  Prime divine during creation of the Cosmic, reportedly created 8.4 more million of active and inactive souls of different nature after which he created Deva Ganas, Asura Ganas serving in Deva Loga, Vedic sastras, Lord Sun and Lord Vayu to establish the concept of Dharma. 
<br /><br />
Once the cosmic embodied with cycles of Yugas and varieties of creatures were created, Lord Adi Brahma, named the first Yuga as ‘Neettiya Yuga’. A fire ritual (Agni Kund meant for performing Yagna and Homa) was performed by Lord Shiva to incorporate appropriate aspects for the universe, in which, host of divine forces besides Lord Vishnu and Lord Brahma participated to discuss the fabric of attributes and aspects to be incorporated in the universe. As the discussion continued, an evil asura called ‘Kroni’, emerged from the Agni Kund and within days of his appearance, he began terrorising the Celestial forces, destroyed the divine abodes and even attempted to destroy mount Kailash. Realizing the danger posed by the acts of the asura, Lord Maha Vishnu sat in penance seeking powers from Lord Shiva to annihilate Asura Kroni and to save the divine abodes and the Celestials. Lord Shiva while granting the boons, instructed Lord Maha Vishnu to kill Kroni by cutting him into six pieces, further indicating that all the six pieces of fleshes would again get birth in some form of an Asura or Monster in the Yugas to follow, and therefore Lord Maha Vishnu too would have to incarnate repeatedly in different forms to annihilate the Asuras born out of the flesh of evil Kroni in course of time in each of the Yugas.   
<br /><br />
<div style="padding-left:50px;">
    ukattuk kukame uttamannay nipiraantu<br />
akattuk kavanpiraappu arru yukamatilum<br />
untu mavanncivann uyiralivu vantavannal<br />
pantu natuukkettup pavi yavannuyiraik<br />
konnrupot tenarakak kuziturkka nalvarugkan<br />
Enntu vitaiotuttar icurarka nammannai – Akilathirattu

</div>
<br /><br />
After Lord Maha Vishnu slayed Kroni into six pieces, ‘Neettiya Yuga’ ended. In subsequent Yugas, in order to save Dharma which were under threat by the asuras born, Lord Maha Vishnu annihilated several asura forces born from the flesh pieces of slayed Kroni. He killed demon Gundomosali in ‘Chatur Yuga’, Thillai Mallaan and Mallosi Vahanan in ‘Nedu Yuga.  In ‘Kretha Yuga’ the fourth yuga, the two demons Singha Mugha and Soorapadma who carried boons of invincibility, when ruled the universe with tyranny, Lord Vishnu incarnated as Lord Muruga and annihilated them with his trident. Since the Yuga had few more years to vanish, Singha Mugha was made to take birth as Hiranya who was also annihilated by Lord Vishnu in the form of Lord Narasimha who was neither human, nor in animal form, and killed him with his strong nails without using any weapon. He killed him on the doorstep of the palace at ‘Sandya Kal’ meaning twilight period when Sun fades away and Moon raises.  In the fifth of the Yuga called Thretha Yuga, demon Ravan who carried three and half crores (3½) of rare boons was killed by Lord Maha Vishnu, in the form of Lord Ram. 
<br /><br />
In the sixth of the Yugas called ‘Dwapara Yuga’, Lord Maha Vishnu incarnated as Lord Krishna and attempted to reform evil minded Duryodhana by way of counselling.  When Duryodhana refused to take the good advice of the Lord and waged war, Lord Krishna was left with no option but to side with Pandava brothers to annihilate the evil Duryodhana and made Pandava brothers’ the rulers of the land.  Lord Krishna realized that the purpose of his incarnation had been completed and decided to return to Srirangam shedding the body of Lord Krishna. In order to end the incarnation, he enacted a drama for his own disappearance by resting in a forest area, when a misunderstood hunter’s arrow pierced through the foot of the Lord, thus making the mortal body fall lifeless. Lord Krishna who was residing inside the body immediately quit the body of illusion and proceeded to his abode in Srirangam. 
<br /><br />
On way to Srirangam, when he reached the hillside of mountain Arigona, he saw seven celestial maidens namely Maragatham, Valle, Valli, Saligai, Sarakathakanni, Sarithai and Arimadavam, all residents of mount Kailaya. The maidens used to come there every day, played for some time in the forest grove, took bath in the river and collected sacred water in their hands to anoint their Lord Shiva by way of worship.  When Lord Maha Vishnu went and stood before them in the form of a mendicant, they could not recognise him and gave way to the mendicant to move, but Lord Maha Vishnu in disguise of a mendicant, asked them to offer worship to him too since they had done enough service to the Lord of braided hair, meaning Lord Shiva. The maidens turned down his request conveying that they cannot even think of offering worship to anyone other than their own eternal Lord sitting on the taurine (Nandi), let them be anyone- Deva Rishis, Maharishis or even Lord Thirumal, meaning Lord Vishnu without knowing that the mendicant was none but Lord Maha Vishnu in disguise. 
<br /><br />
Angered by their refusal to offer worship, Lord Maha Vishnu threatened that they would not be able to carry the water from Ganges anymore to anoint their Lord.  Immediately he brought the entire grove under the grip of unbearable chillness and stood there in the form of a fire after absorbing seven forms of semen from seven worlds of the universe.  Unable to bear the extreme chillness, the maidens went near the fire and stood around it as if they were hugging the fire, unaware that the fire was Lord Vishnu in disguise. Instantly they lost their modesty, and gave birth to seven children.  Since they lost their modesty, they could not collect water in their hands to anoint their Lord. Heartbroken celestial maidens felt ashamed that since they had lost their chastity, they would not be able to collect water anymore to anoint their Lord.  Therefore, leaving the children born to them lying there, they went to the forest and sat in penance with plea to get married to the same mendicant who outraged their modesty. 
<br /><br />
<div style="padding-left:50px;">
    Intengkal karpai edazitta mamunnivar<br />
vantegkal tammai malaiyita venumenttu<br />
pantut tannaminnar pavaiyezhu perum<br />
icurare thanjamenaa iruntar tavacatile – Akilathirattu

</div>
<br /><br />
Lord Maha Vishnu named the seven male kids as Sanar, Sandroars, and Nadalvar. Further he anointed them with 13 more such names, left them under the custody of Goddess Bhadra Kali, and proceeded to Srirangam where he rested in full purview of the universe. Mother Bhadra Kali, natured those boys very well, and imparted master arts and skills of several in nature, and thereafter took their help to annihilate Thakkan. Subsequently she got them married to the seven maidens, daughters of King Nriputharajan and settled them in seven separate houses specially built for them, where they lived with all comforts and glory.     
<br /><br />
During the same period of time, in Deva Loga, Guru Muni (Sage), along with the Celestials went to Lord Shiva and reminded him that appropriate time to bring out the Kali Yuga in the universe had already arisen. Acceding to the request of the Sage and the Celestials, Lord Shiva converted the last and sixth flesh of slayed Kroni into an asura named Kalian representing Kaliyuga who in fact was Duryodhana in his previous birth. Lord Shiva bestowed several boons to Kalian. He transformed one of the bones of Kalian, taken out from his hip into a female embodied with half the strength of Kalian and got Kalian married to her.  Henceforth Kalian will be referred as Kalineesan or evil Kali too. After obtaining several boons from Lord Shiva, as Kalian was returning to his place, Lord Maha Vishnu in disguise of a Pandaram (mendicant), wearing torn clothes, uncouth in appearance with braided hairs, blocked his way demanding that he part away some of the boons he received, lest he would not allow Kalian to continue the journey unless he defeated him (Lord Maha Vishnu in disguise of Pandaram) in a fight.  Kalian shied away to fight with him saying that even women would laugh if he chose to fight a Pandaram like him who had no weapons in hand to fight.  On insistence from Lord Maha Vishnu, to fight or part with the boons, Kalian promised on oath that he (Kalian) would never ever harm any Pandaram or mendicant, and if any Pandaram or mendicant was harmed by him (Kalian), the entire boons possessed by him would be lost.
<br /><br />
Dear devotees, only to snatch away the powerful boons in possession of Kalian alias Kalineesan, Lord Maha Vishnu appeared in guise of a Pandaram and met Kalineesan in the name of ‘Shri Pandaram’ so mention Holy Akilathirattu in beautiful tamil ‘yeraniyum maayon ivvulagil thavasu panni kaaranam pola seitha kathai’ meaning the story of the most beautiful and elegant Lord Maha Vishnu who undertook a unique penance for specific reason. 
<br /><br />
Once Kalineesan descended on earth, the entire atmosphere turned from good to worse. The evil forces unleashed intolerance, impiety, wickedness, unrighteousness and impudence all over the universe. The folks began ignoring the doctrines of sacred Vedas. Good animals, birds and other living creatures deserted the main land and went to the forest in search of Lord Mahavishnu, who appeared before them in the form of a Mendicant (Pandaram in Tamil) and advised them to stay in penance seeking incarnation of Lord Mahavishnu to re-establish kingdom of righteousness (Dharma) and take over the reins of the state. On the strength of the boons, Kalineesan spread hatred amongst people of different castes, kept them divided into many castes, created fiction to rebel against each other for their own selfish interests.  Burdening the folks with heavier taxes, he not even spared the sacred Mangal sutra (Wedding badge or string or thick yellow thread with a symbol knotted in the neck of bride) or dry leaves falling from the trees from the purview of taxation. 
<br /><br />
Cows were made` to starve.  When canon of justice and righteousness in the universe began to get destroyed, folks remained divided over caste lines, ethics, moral and human values dwindled to their low ebb in Kali Yuga. In view of the atrocities committed by Kalian, nature’s fury caused heavy downpour and torrential rainfall which lashed the state inundating many areas. Further the walls of huge Vaigai river burst and water began entering into the cities. The Chola King Kari Kalan immediately summoned the Sandroars and ordered that the breach be sealed with mud and sand brought in the baskets, ignoring the fact that the Sandroars too were also Kings of his stature. When they refused to carry out his order, he got two of them trampled to death under the feet of an elephant. When Lord Narayana heard of it from Saint Vidyathara, he immediately came there in the name of Chokkar, himself carried mud in a basket for pudding (called puttu in tamil given as alms for services) in between taking lashes from the guards, but ultimately ensuring that the life of remaining five Sandroars were saved. He then went to Srirangam in fit of rage and took rest there. 
<br /><br />
Rogues and criminals exploited the people. Thefts, fear and slovenes increased, gambling and corruption were rampant and murders and killings became order of the day. Sacred texts of ethics and morals (Shastra) tweaked and concocted to suit the rulers resulting in the folks adapting wrong rituals and practices. Maladies of mind and body increased and morality reached the lowest ebb. Folks fell prey to the politics of caste and opposed one other on caste lines. Kalineesan misguided the folks with falsehood and hatred.  The Europeans adapted divide and rule policy and ruled the state unleashing terror and fear.  Humanity and spiritual practices degenerated, chanting of sacred name of Hari stopped.  Rulers after rulers were wicked and under the influence of Kalian, dumbfounded people with the money power they wielded. At one period of time there were none to counter the influence of Kalian who ruled his land for over several thousand years by deceit and firmly established his influence and power throughout the vast land.
<br /><br />
Due to the influence of Kali illusion, when the Vedic Pundits of Srirangam temple were misbehaving with women inside the temple premises, vexed Lord Maha Vishnu decided to go away from there. In the meanwhile, Maharshi Shuka Brahma too requested Lord Narayana to go to Thiruvananthapuram to reform one of the Kings of Travancore to mend his ways who under the influence of Kalineesan ruled the land oppressing hapless clan called ‘Sandroars’ (highly poor people, oppressed and suppressed by the then rulers, belonging to over eighteen different castes like Nadars, Parathavar, Mukkuvar, Pulaiyar, Ezhavas, etc.). It firmed up the decision of Sri Maha Vishnu to leave that place. On way, he expediated the curses of 55 brahma rishis, standing as stone statues due to curse received from Lord Brahma, for having attempted to steal the birth-death account book privy to Lord Brahma. He also expediated the curse on a beautiful maiden called Ekkaala durkai, who remained a small mount on account of a curse received from Lord Shiva.  She wanted to take revenge on Lord Yama who killed her husband out of lust on her, and Lord Shiva advised her to wait for some time before Yama could be punished, but she defied his directive and hence got his curse.  While expediating the curse, Lord Vishnu restored her beauty and indicated the time frame when Lord Yama would get due punishment for the crime.   Similarly, the Lord appeared before another maiden who was in penance seeking punishment to Chitra Gupta the deputy to Lord Yama, who too killed her son out of lust on her. She wanted Chitra Gupta to be punished.  A Cow was also in penance seeking her son be reborn to her as her calf. Lord Vishnu revealed to both the time frame for the reward and then proceeded towards Thiruvananthapuram. 
<br /><br />
One of the Kings of Travancore under the influence of Kalineesan raised a big temple for Lord Mahavishnu (Ananta Padmanapa) in Thiruvananthapuram and performed rituals regularly. Unhappy over the rule of the King who oppressed and suppressed the hapless ‘Sandroars’ (the eighteen downtrodden folks like Nadars, Ezhavas, Baratava, Mukkuvar, Pulaiyar etc), infuriated Lord Maha Vishnu went to the ruler and warned him that if at all he wished his dynasty to continue the ruler of the land, then he should immediately desist from harassing or oppressing the hapless folks, who were the kins of Goddess Bhadra Kali born in the clan of Sandroars.  Lord further advised him to treat them with dignity like any other folks, lest ruin was certain to him and Kingdom which he had inherited would be lost. But the adamant King under the influence of evil Kali was determined not to change his style of function till he breathed last, no matter what may happen to him and openly displayed his hatred on Sandroars. Infuriated Lord Maha Vishnu challenged the King that though for the present he was proceeding to Tiruchendur, he would soon come back to unite the folks of all caste, make them love each other, and then destroy the Kingdom of the arrogant ruler.  The Lord left Thiruvananthapuram and went to Tiruchendur. 
<br /><br />
As the oppression and suppression of Sandroars continued in the rule of Kalian, the Celestial along with Goddess Parvathi met Lord Maha Vishnu and requested him to intervene and save the Sandroars from the oppressor. Realizing that the Kali maya (illusion of Kali) cannot be won over with weapons, Lord Maha Vishnu directed the Celestials, Rishi Munis, several other saints and Devaganas residing in divine abodes like Kailash, Vaikunda, Swarga log, Siva log, Yama log and other abodes to go and take birth in the clan of Sandroars.
<br /><br />
Next, when Lord Shiva and Goddess Parvathi along with Lord Maha Vishnu met the Celestial maidens who were sitting in penance in the forest, Lord Maha Vishnu not only assured them that he would marry them when he incarnated as Lord Vaikundar in Bhoologa, but also return their sons. He directed them to go to Bhoologa, take birth and wait for his incarnation.  Thereafter Lord Maha Vishnu also requested Goddess Mahalakshmi to go and remain inside the sea radiating golden rays like a huge flame of fire (Magara) since he was also destined to incarnate in Bhoologa to destroy Kalian. Heeding to his request Goddess Mahalakshmi too proceeded to Bhoologa and remained seated deep inside the Tiruchendur Sea radiating golden rays like flame of fire (Magara) around her. 
<br /><br />
As time passed, one day Lord Maha Vishnu suddenly recollected his earlier promise that he would incarnate in the form of a Pandaram to protect the sufferers under the influence of Kali and also remembered that his consort would be waiting inside the sea of Tiruchendur. In order to reconfirm whether appropriate time destroy evil Kali had arisen, he sought the advice of Veda Vyasa, who re-confirmed that the right time to take incarnation as Lord Vaikundar had already arrived.
<br /><br />
<div style="padding-left:50px;">
    munne parantan mozin tatinpatiye<br />
tarma puviyala suvamini rakavenrum<br />
turmak katankazittor cukamaka vazvarenrum<br />
akamattaip parttu ativi yacurarum<br />
nakattanai kitanton nattama tayuraittar – Akilathirattu

</div>
<br /><br />
The Lord realized that he had to publicly incarnate in the southern end as son of Goddess Mahalakshmi to confront Kalian. Without wasting time further, when Lord Maha Vishnu immediately proceeded to Bhoologa and reached the seashore in Tiruchendur, he was warmly welcomed by both Maharishis Rishyasringa (Kalaimuni) and Pathanjali (Gnana Muni) who prostrated at his feet and offered their salutation. Lord asked them to be with him.  
<br /><br />
<div style="padding-left:50px;">
    pantavar tamakkayt tonntti pakaitannai mutittu mayon<br />
vinnrriya kaliyann vanta vicannattal kayilai yeki<br />
cantaavar tamakka yintat taraniyil vanta nayam<br />
aantavar aruli ceyya ammannai ezutalutten – Akilathirattu

</div>
<br /><br />
One of the Devaganas had to take re-birth in Bhoologa as Sampoorana Devan alias Muthukutty (he is referred to only as Sampoorana Devan in Akilathirattu) to atone a sin accrued for showing lust and evil thoughts on the wife of another Devagana.  Once taken birth in Bhoologa, he married the same girl who had also taken rebirth, excessively enjoyed worldly pleasures and lust with her and fell seriously ill as destined and was brought to the seashore.  He got relieved of the curse since Lord Maha Vishnu had earlier promised that his curse would be removed when he (Lord) incarnate in Bhoologa. When Sampoorana Devan reached the seashore, Lord Vishnu too reached the seashore and relieved the curse of Sampoorana Devan as promised previously.
<br /><br />
<span style="font-size:16px;color:Maroon;">The incarnation of Lord Mahavishnu in Kali Yuga:</span> As prophesied in the Vedas, to destroy the influence of Kali along with the boons evil Kali carried, Lord Maha Vishnu descended on earth and entered into the sea of Tiruchendur where his consort Goddess Lakshmi was waiting for him inside the sea. He pushed the mind of Goddess Lakshmi into state of perturbation, aroused feelings in her and entered into her body only to come out himself in the form of a formless child in the universe on the 20th day of Tamil Month Masi in the year of Kollam, 1008 corresponding to Friday, the 1st March 1833 CE.  By the time the formless Lord reached the seashore, he disguised himself as Lord Vaikundar, the tenth incarnation of Lord Maha Vishnu. The sacred Pathi called ‘Avatharapathi’ lies in Tiruchendur seashore. This is one of the sacred Pathis in the Narayanaswami vazhi also called Ayya Vazhi.  
<br /><br />
<div style="padding-left:50px;">
    antaa yirattu ettatile atanne mata maciyile<br />
nanrag katalin karaiyanti nara yananre pantaram<br />
kuntan tecca napuriyil kontom palli tarmamuttuu - Akilathirattu
</div>
<br /><br />
After reaching the seashore, Lord appeared in the form of a Pandaram (Mendicant), dressed up in ochre robe, braided hair, sacred white mark on forehead, Rudraksha mala (garland) around the neck, Rishi’s Wand and a Kamandal (a water-vessel of a religious mendicant) in hands and as if he was a Pandaram.  The celestial forces and Devaganas waiting for his arrival, prostrated at his feet and offered their obedience with lullabies and danced along the entire route in joy.
<br /><br />
<div style="padding-left:50px;">
nallana rayanarum namamani vaikuntarayc<br />
cellat tiruvulamayc cimaik kurrutiyumay<br />
manitavata rametuttu vaikunta vacavanum<br />
panitavazum pattiniyal palaruta vagkicattil – Akilathirattu

</div>
<br /><br />
Once, Lord Vaikundar came out of the seashore, after suitably advising all those assembled in the seashore, he walked towards Swamithoppu from Tiruchendur. On his way, the Lord established a Shivalinga, in a place called Moolakundapathi, also known as Ambalapathi, offered prayers to it and proclaimed that he would come back again. 
<br /><br />
On reaching Manavaipathi in Swamithoppu, Lord Maha Vishnu instructed Kalaimuni (Rishyasringa) to send communique to the ruler of Kali, the reasons for his incarnation and his preaching. Without wasting time immediately Maharishi proclaimed to the universe through a message saying ‘since Lord Narayana himself has incarnated as Lord Vaikundar, in the southern end in the month of Masi, in the year 1008, no one should pay offerings, be a pole bearer, or feel fear of other divines, but at the same time remain honest, free of corrupt practices. 
<br /><br />
In one of the earlier Yugas, Arjuna sat in penance in Tamaraiyur Pathi in Poovandar Thoppu (Thoppu meaning grove) seeking Pasupatham (Most powerful weapon in the arsenal of Lord Shiva). News flashed all over the land that Veera Narayanar (Vaikundar) was in penance under a mango tree in the same place where Arjuna had earlier penanced. Lord Vaikundar called the demons and ghosts and warned them to keep away from the worldly affairs as he was set to examine the state of affairs of the land in the next ten months and thereafter rule the land bringing everyone under one umbrella of his rule. Those who could not understand the power of Lord Vaikundar called his proclamation as sputter and twaddle. Unmindful of the comments, Lord Vaikundar kept himself cool and decided to examine the state of affairs staying as one amongst the folks. He sat in penance for six years spread in three phases, seeking grace from Lord Shiva. The first for the destruction of the Kali yuga and dawn of Dharma Yuga, the second for the removal of caste barriers and emergence of good creatures, and lastly the third for the well-being of the Saptha Kannigas along with upliftment of Sandroars. The then Poovandar Thoppu has been the present land of Swami Thoppu the northern gate area of which is where Lord Vaikundar sat in penance. The Swamithoppu Pathi has been referred as Manavai Pathi and Tamaraiyur Pathi in Akilathirattu. 
<br /><br />
In Swamithoppu Lord Vaikundar stayed in the form of a mendicant and when he wished that the folks of fifty-six countries come to him, attracted by his mind voice, thousands of  folks from   eighteen castes like -Sanar, Idaiyar, Vanigar, Nanatha Kaveri, Nalla Tulupattar, Shudra, Brahma, Tholvanigan, Paraiyan, Uthira Nisan, Uzhavan, Kuravan, Kammala Neelan, Karumaravan, Paravan, Vemma Naasuraani , Sangilian, Megavanna Idaiyaar etc flocked to Swamithoppu every day where Lord Vaikundar established land of equality by making people belonging to all castes draw water from the same well for bathe and daily chores including drinking purpose.
<br /><br />
When the philosophy of Lord Vaikundar spread across the land, people belonging to various castes began to come there, surrendered and offered worship to him. Lord Vaikundar told everyone that as prophesied in the Vedas, he had incarnated  in Kaliyuga to establish rule of Dharma and the pious people reborn would witness the change. He appealed to the folks to surrender at the feet of the Lord firmly who was the creator and protector of the universe. All should live in harmony, remain firm adhering to basic rituals and loyal to the Lord.  His teachings were directed not only to the humans, but also meant to the birds, animals and all other living beings including plants and trees, reptiles, rough rocks and stones which were nonliving beings (There exist some form of life in the static beings too). The folks firmly believed that Lord Narayana has indeed incarnated as Lord Vaikundar as fore told by Veda Vyasa in the Veda Agama and therefore surrendered at his feet. They also firmly believed that the path had been laid for the destruction of those opposed to Lord Narayana.  
<br /><br />
At the end of the penance, the folks went to Lord Vaikundar and lamented that they were unable to bear the atrocities of evil demons and spirits under influence of Kalian. On hearing their woes, Lord Vaikundar quickly visualized what had happened and the extent of atrocities committed by evil Kali.  After evaluating the past atrocities of the evil forces and reconciled with the rules in Agamas, it became clear to him that the time to completely destroy the powers of the demonic forces had ripened. Therefore, he quickly acted to curb them in the next few minutes. He destroyed the powers of the evil ghosts and spirits and renamed five evil warriors called Pancha Devas or Guardian deities -Sudalaimadan, Kattayeri, Palavesam, Masanam, and Kathavarayan- as Karudarasan, Similarasan, Thertagan, and Tuttiveeran and as Therkudayon. Their divine powers were replaced with modified powers since they had earlier accepted the animal sacrifices against the dictums of the Lord. Thereafter he kept them by his right side in the name of ‘Yeval Seevaai’ (meaning the one who obeyed his command). Those developments were viewed by Akilathirattu as 'transformation of the status of the demi gods’. In the act of next, Lord Vaikundar decided to snatch away the powers of evil magicians engaged in the art of black magic, sorcery etc., and sent wild animals to attack them. The magicians could not contain the anger of those wild animals with their magical powers and therefore on the advice of a lady fowler (who forecast the future in trance), they surrendered at the feet of Lord Vaikundar assuring that they would henceforth never indulge in the art of evil black magic or sorcery. The folk of the land felt happy and heaved sigh of relief over the development.
<br /><br />
Severe dress code existed in the rule of Kaliyarasan (King) to those belonging to the oppressed and suppressed folks. The male folks were not allowed to wear turban, robes or allowed to cover their upper body or wear dhotis extending below knees touching toes.  Similarly, the females were not allowed to cover their upper body. Hence Lord Vaikundar advised that those norms be defied, males should come wearing turban or a head gear and similarly the females should cover their full body with cloth (Sari). The Lord prophesied that ‘in future there would only be givers and not takers. If the folks desired re-establishment of Yuga of Dharma, then they should not only love each other, but also desist from practicing animal sacrifices with sheep, goats and chickens. 
<br /><br />
In order to eradicate the evil practice of untouchability, he picked up sacred clay (Thiru Namam) from the ground and personally applied it in the form of a mark on the forehead of everyone. In those days every caste had their own community well to fetch water for use for all purposes. Folks of other community were not allowed to use them. In order to establish oneness of feeling in all, he enforced that everyone, irrespective of their caste should fetch water only from one well available in the place of his stay for use of daily chores. This practice of using water from the common well promoted qualities of equality, social justice, self-respect, fearlessness, and life of virtue. Lord Vaikundar settled in a small town called Manavai Pathi also called Tamaraiyur Pathi in the southern end. 
<br /><br />
As Lord Vaikundar continued to perform wonder social transformations, five of the folks became his closest disciples. They were Shri. Sivanandi, Shri. Pandaram, Shri. Alagesan, Shri. Subbaiah and Shri. Arigopalan, all of whom carried title Citars, were none but Dharma, Bhima, Arjuna, Nakula and Sahadeva, the five Pancha Pandava brothers in the past birth in Dwapara Yuga. Hence Lord Vaikundar made them get birth in Kaliyuga to become his disciples. One amongst the five was Shri. Arigopalan Citar who scripted Holy Akilathirattu the so-called Veda Agama.
<br /><br />
As each day passed, when folks of different castes, attracted by his charisma, and the teachings continued to flock around Lord Vaikundar, it became eye sore to the upper caste people. The ruler was also concerned that a separate socialistic state of society was slowly and steadily getting firmly established in Swamithoppu. Failed to foresee the personal humiliation and disgrace awaiting the ruler, descendent from the flesh of Kroni, he decided to get Lord Vaikundar arrested. Prior to it, he called a Vedic pundit to analyze all aspects and forecast whether the planetary positions were really inimical or favorable to him (King).  After thoroughly analyzing the planetary positions and other astrological aspects, the pundit opined that as per his reading, the effect of Kali has spread far and wide to seven worlds because of which infuriated Lord Maha Vishnu was set to take birth as human to destroy Kali and to bring everyone under the umbrella of one rule called Dharma, further indicating that the ripe time had already come for such a change.
<br /><br />
But the unconvinced ruler wondered whether the Lord would incarnate in the most downtrodden caste of Sanar instead of taking birth in upper castes like Potthi, Namboothri and Brahmin. In an act of haste, the ruler directed his Minister to immediately proceed to get the Lord arrested. Sensing trouble, an elderly person (Poovandar) from the shepherd clan told the ruler that Lord Maha Vishnu does not discriminate anyone based on caste as he was creator of the universe and would only confine his acts to the purpose for which he had incarnated. It was undoubtedly clear that the Kali Yuga had dawned and his incarnation certain to destroy Kali. He drew the ruler’s attention over the past when Lord Maha Vishnu appeared in the clan of Shepherds, Nomadic, and also as Visu and a Hunter.  Since the Lord pervades everywhere, he would never discriminate anyone and the mysterious acts of him cannot be understood. 
<br /><br />
<div style="padding-left:50px;">
    canennak kulattil mayan sarvaroenn renna ventam<br />
pananayt tonri nirpar paraiyanayt tonri nirpar<br />
tunenat tonri nirpar tolanayt tonri nirpar<br />
anenat tonri nirpar avaruru ketti lIro<br /><br />

kucavanin kulattil vantar kuravanin kulattil vantar<br />
macavenak kulattil vantar matenak kulattil vantar<br />
vicuvenak kulattil vantar vetanin kulattil vantar<br />
acuvenak kulattil vantar avaruru ketti lIro<br /><br />

evvitan tanay mevi iruppavark kentac sati<br />
avvita maka tenru avartalla matta raiya<br />
cevvita mapon sutsam ceppitat tolaiya taiya – Akilathirattu

</div>

<br /><br />
The saner advice of the elder fell in deaf ears of the ruler who failed to foresee the disaster awaiting him or the true spirits with which it was told. He lost his mental balance, got Lord Vaikundar arrested and imprisoned him in a place called Singarathoppu in Thiruvananthapuram. Though the ruler gave Lord Vaikundar alcohol mixed with poison to drink, it did not harm Lord Vaikundar in any manner. The ruler then brought a starving tiger in a cage and pushed Lord Vaikundar inside the cage hoping the tiger would eat him. The folks who were watching the cruel act cried aloud in helplessness, but the Lord counselled them ‘to remain calm since he had incarnated to end the evils of Kali. He claimed himself to be embodiment of Trinities, pervades everywhere including inside the animals, birds, reptiles and all other living beings, hence they need not worry about the tiger, which would definitely recognize divinity in him’.  
<br /><br />
<div style="padding-left:50px;">
    nattuk karivirinan nara yananumnan<br />
patci paravai palaciva centukkalai<br />
niccayamayp pataitta nilavannaa natanumnan<br />
manne zalanta mayap perumalnan<br />
vinne zalanta vishnu tiruvulamnan<br />
ekam pataittavannan engkum niraintavannan<br />
akapporul muntrum atakkamon ranatinal<br />
natak kataltuyinta nakamani nanallavo<br />
civacentuk kellam civanum nanallavo<br />
innica naellam ennaiyai yatiruntal<br />
minnilattil nanpataitta miruka mariyato! – Akilathirattu
</div>
<br /><br />
The starving tiger which was pushed inside the cage looked at the Lord for a while and instead of attacking him, it went near him, touched his feet as if prostrating, and sat by his side in silence. An impatient soldier prompted the tiger by pricking her with a long trident to attack the Lord. The tiger held the trident tightly under her body. In order to repick the tiger when the soldier attempted to pull back the trident with full force, the animal just released her grip over the Trident allowing it to fly back like an arrow and hit a Brahmin standing near the cage instantly causing death to the Brahmin. The ruler panicked because killing a Brahmin was greater sin than killing thousand cows, and he feared that his land has accrued sin. Everyone realized for certain that Lord Vaikundar indeed was divine incarnate, manifested to save the mankind from the evils of Kali.
<br /><br />
Though the ruler released Lord Vaikundar from prison, the Lord refused to immediately leave the place and continued to stay back in Thiruvananthapuram for some more days.  He informed the folks that he would leave the place on nineteenth day in the month Maasi and proceed to the eastern direction and those who wished to go along with him could proceed with him holding their spirits high like a bright lamp. The folks listened to him carefully and fell at his feet feeling their nightmare had ended. They got him seated on a cradle like palanquin and walked carrying him.  The Holy Akilathirattu viewed it as the beginning of the end of Kali along with the boons it carried since Lord Maha Vishnu, who was in disguise of a Pandaram had been maltreated.
<br /><br />
In order to strengthen the will power of the folks who followed him, Lord Vaikundar when reached Tamaraiyur Pathi, commenced a unique penance called Thuvayal Thavasu in which he enforced everyone to take ritual bath three times a day, wash their clothes daily, eat at noon with balanced food and offer prayers to him (Lord) in the language known to them. Besides they should also perform three-time prayers called Uga Padippu - both in the morning and evening and Uchchi Padippu in the noon (The Uga and Uchchi Padippu means Group prayer song sung in chorus to control the wavering mind and to beget the divine bliss).  With an intention to surrender at the feet of their Guru, who is ultimate (supreme being), they went to the northern entrance in Dwaragam Pathi called Vagai Pathi and penanced under the clear sky.   He enforced community dining where everyone irrespective of their caste and status- poor or rich- would sit and dine together in a common venue. When time passed, Lord Vaikundar appeared in the dream of one of the Sandroars to reveal that in a place called Mutta Pathi on the south-west, under the rule of Mukund (Lord Maha Vishnu), the victory flag of his empire has been established after destroying the evils. The greatness of the place cannot be explained in mere words. Those who stay there would   enormously benefit beyond their belief. When the folk conveyed his dream to everyone, all of them decided to move there. 
<br /><br />
<div style="padding-left:50px;">
vazva tirkurai varatu makkalug kilaika lotu<br />
tazva tillai vannam tavamatu valarva takum<br />
nalvazip palanun takum narana raruli nale<br />
alvatu titana menru atilava rirunta rantee – Akilathirattu

</div>
<br /><br />
Those who came to Mutta Pathi continued to perform the thavasu (rituals) honestly. They took ritual bath for three times, wore washed bright whitish clothes unlike in the past, and their skin gilded like that of Lord Maha Vishnu, perhaps because Lord Maha Vishnu himself had incarnated in their clan. The other caste folks wondered how Lord Maha Vishnu, by incarnating amongst the Sanar folks, brought transformation in their life and inculcated the habit of eating food at the right time, and the art of praying with hymns.  They felt jealous that even the washed clothes of the upper class like Potti, Namboothri and Brahmins were not as bright as the Sanars who stayed with Lord Vaikundar. They could not digest the fact that the saris worn by the female folks of Sanar were sun bright compared to ladies of the upper castes. They grudged to notice the feelings of Sanars that they were no more mere workers who climb on the Palm and Coconut trees to fetch fruits to others.  After some time, Lord Maha Vishnu decided to send all of them back to their respective homes.
<br /><br />
<div style="padding-left:50px;">
    nara yanakkuruvai nalu maravamal<br />
peraka veyiruntal perungkaluk kekitaikkum<br />
anna malakkum atit tirunetumal<br />
munanavan tanperal muttirika littatinal<br />
centra itamellam cirappatika mugkalukku – Akilathirattu

</div>
<br /><br />
Later, Lord Maha Vishnu, by his mystic powers, summoned the seven maidens who had taken birth as Saasthirakanni, Kamalakanni, Mogakkanni, Moolakkanni, Kadungsakthi, Deivakkanni and Arimadavai. Once they arrived, he disguised himself into the form of a Pandaram groom, clad in Saffron robe, a garland made of Rudraksha bead adorning the neck, Thulsi leaves on his head, a stick and Kamandal (a water-vessel of a religious mendicant) in hand and tied the Mangal sutra (Wedding badge or string or thick yellow thread with a symbol knotted in the neck of bride) on their necks which he was carrying with him. While tying the knots, he blessed ‘May the land of Dharma flourish, let the Mangal sutra remain forever in the Yuga of Dharma, may the ladies and Sandroars live with dignity with the blessings of Lord Shiva and other divines. The place where he married the seven maidens is called Tamaraiyur Pathi also called Swamithoppu.  Further, Lord Maha Vishnu remarried goddess Seethalakshmi and as promised to the seven maidens earlier, he returned back the sons (delivered by them in previous Yuga) born to them. Everywhere folks were jubilant to see the events.
<br /><br />
<div style="padding-left:50px;">
tutiyitaik kanni marait tirumanan tirumal ceytu<br />
kutipukazc cantoor makkal kuravaikal muzakkat totu<br />
titirenat terukkal currit teviyu manna rakap<br />
patimicaip patiyi nulle patintuvan tirunta rantae – Akilathirattu
</div>
<br /><br />
When Kalian began to proceed to Bhoologa with the boon he carried from Lord Shiva, Romarishi who was present in Deva Loga inquired from Lord Shiva when would Kali get destroyed. Lord Shiva replied that once the important divine mothers (not the seven maidens) got married in full purview of everyone in Bhoologa, count down for destruction of evil Kali will begin. When curious Romarishi, wanted to know who was likely to marry the divine mothers, Lord Shiva pronounced that when Lord Narayana incarnates as Lord Vaikundar embodied with the divine powers of us (Trinities -Brahma, Vishnu and Shiva) to destroy evil Kali and pick up good folks, he would marry the  divine mothers (except the seven maidens whom he had already married) and live  there happily with them.
<br /><br />
There in Bhoologa, in Tamaraiyur Pathi Lord Vaikundar continued to live happily in guise of human along with the seven maidens he had married earlier, intermittently displaying several divine plays. The place where the seven maidens lived is called Thottil Pathi. Prior to coming to Moolakundapathi after incarnated as Lord Vaikundar, as he walked towards south from the seashore, he established a Shiva ling in Moolakundapati, also known as Ambalapathi, offered worship and then hid it before proceeding further. He took an oath that he would come back again to worship the same Shiva Ling after performing several acts of divine plays, marry the seven maidens and completion of other duties. Because Lord Vaikundar had taken the oath thus, he decided to immediately go and settle in Moolakundapathi along with other folks who followed him. Lord Vaikundar publicly pronounced that ‘Moolakundapathi was a divine land, free of sins and those who visit there would be blessed with what they desire’. Accordingly, on reaching Moolakundapathi, he removed the sins of the folks which they had accrued out of misdeeds out of ignorance and lived there happily along with them. Every Tuesday, he appeared before the folks in his original form and prophesied the events forthcoming. 
<br /><br />
While living so in Moolakundapati, Lord Vaikundar realized that the time had come as foretold in the Agama to destroy Kali Yuga and therefore before going into the act of engaging Kali, he realized that he had to marry in public, enlightened and powerful Goddess Bhagavathi, Mandaikattal, Goddess Valli and Goddess Devasena.  He married all of them in Moolakundapathi Pathi also called Ambala Pathi   in full public view.   Accordingly, he married Goddess Bhagavathi (an aspect of Goddess Parvati) in the form of Lord Shiva, Mandaikattal (an aspect of Goddess Saraswathi) in the form of Lord Brahma and finally Goddess Valli and Goddess Devasena in the form of Lord Muruga.  He completed those tasks too in full public view.
<br /><br />
Listen Sandroars, in each of his incarnations in various Yugas, Lord Maha Vishnu had firmly established that the fleet of divines worshiped were not different from each other and though they may appear in different forms, they were all mirror images of Supreme Lord. By display of Visvaroopa darshan, he displayed the theory publicly. Only in order to deeply etch this fact into the minds of mankind and to ensure that they do not stand divided while worshiping different divines, he re-enacted several divine marriages. While Lord Maha Vishnu was happily spending his time with his followers, he told the Sandroars that he was delighted on the establishment of worship places (Pati) in their hometowns. They should spread the story of his ten incarnations, and the divine play enacted in which he measured the entire three worlds (Eternal space above, Earth and Underworld below earth) in three steps. Thereafter he visited the small shrines (Nizhal Thangals) built by the Sandroars, partook food, and continued to display divine acts of different kinds in nature.  The Lord took part in the feast along with his consorts in a place called Virunthetra Pathi also called as Thenthamaraaikkulam Pathi.  The folks eulogized Lord Maha Vishnu thus 'Like the dried crops which await the rains, we were waiting for your incarnation to save us from evil. Please forgive our wrong doings and bless us. We surrender at thine golden feet of thine as thee our savior and divine'. Meanwhile the Lord married in full view of the land another maiden Goddess Bhumadevi (Goddess of Earth), who had taken birth in the name of Goddess Poomadanthai and lived in a place called Soorangudi. While the Lord was returning, the place where the Celestial showered flowers on Lord Vaikundar and his consorts is called Poo Pathi. Thereafter the Lord happily settled in the Pathi along with others. 
<br /><br />
Finally, Lord Maha Vishnu who measured the soil in three steps proclaimed 'the atrocities committed by evil Kali in all the past seven Yugas would be scrutinized and judgment would be delivered based on the atrocities committed by him in the past. The boons enjoyed by Kalineesan would get destroyed, wrong doers sent to hell and the doors of hell would be locked to prevent their escape.  A new Dharma Yuga under the leadership of Dharmaraja would be established in Dwaraga Pathi where pious people would occupy the throne. There would be no inequality and everyone would live under one umbrella of rule’. He further promised that everything would happen in the glorious land of Dwaraga Pathi in full purview of the folks in the fourteen world and the folks could live there happily with their family. After retaining his incarnation in the Kaliyuga for over 18 years and 91 days, Lord Vaikundar realized that his duty was over and therefore decided to go back to Vaikunda. When the Pushpa Vimana (Aircraft) came to pick him up, he asked Maharishi Sathguru who accompanied the aircraft to wait for half an hour. He blessed his loving folks advising them to always remember the Lord in their mind and heart, remain united.  He called them near, gently rubbed their hands over his face and assured that he would in future appear in a new incarnation. He advised that they always remain cool and composed, help each other and live in peace and harmony. 
<br /><br />
At 12 noon on Monday, the 21st Vaikasi in the year Kollam 1026, (corresponding to 2nd June C.1851), Lord Maha Vishnu who had incarnated as Lord Vaikundar to protect and uplifting the life of oppressed Sandroars, ended his incarnation and returned back to Vaikunda.
<br /><br />
The Celestial from Deva Loga showered flower petals over Lord Vaikundar, while other divine forces sang hymns called Tirupattu (Thiru meaning venerable and Pattu meaning song) praising him.  Deva Loga dancers called Rambais (dancers) danced to the tunes of deafening drum beats played by the Sages and Rishis welcoming the Lord Vaikundar. They contended that Lord Vaikundar had indeed incarnated  in deference to the proclamations of Agama texts written several thousand years back. They placed a crown over his head, garlanded him and made him seated on a Lion faced Simhasan (Throne).  Seated on the throne of dharma, the Lord Vaikundar in the universe would be examining the state of affairs amongst the folks, by keeping away the falsehoods, and grace those who walk the path of dharmic practices as laid out in Veda agamas.
<br /><br />
<span style="font-size:16px;color:Maroon;">Lord Mahavishnu’s rule in Dharma Yuga:</span> As foretold in Veda Agama Akilathirattu ‘Lord Shiva, Goddess Parvathi, Lord Maha Vishnu, Goddess Lakshmi, Lord Brahma, Goddess Saraswathi and Vedic Maharishis are going to re-appear at the end of the present Yuga after which new Dharma Yuga would dawn.  As prophesied in the Vedas, Lord Maha Vishnu, would scrutinize all spheres-from sky to earth, and destroy Kalineesan ending Kali Yuga to pave way for the establishment of new Yuga, turning the universe into regenerated golden earth, true heaven, crystal clear sky, pure air, brighter moon, pious humans, new reptiles and other species of life.  As pre planed, on the directives of Lord Maha Vishnu the ocean would clean up the earth and then surrender to Lord. The evil would be destroyed with the birth of folks with good deeds and mind. The Lord would ensure that the overall situation in Dwaraga Pathi would turn splendid. 
<br /><br />
After the universe gets regenerated, the soul of evil Kroni would be paraded before the Lord when he would be grilled for his past acts. The Lord would question him 'Oh, evil, I bestowed several boons and ensured you take births in each of the past seven Yugas. I expected you to lead life of honor with dignity.  But you failed to meet my expectation and I had to incarnate in the form of a Pandaram to destroy the evils which were indulging in heinous crimes. I cured several diseases and ailments of the folks, sprinkling plain water and ensured that the folks with virtue get rewarded and vice punished. I banned the ritual of donations and other such kinds. I increased the determination of the folks. Contrary to what I did, you imprisoned and chained me to humiliate and torture me. Since I was in the form of a Pandaram I could not rebel against you.
<br /><br />
As a mendicant, I led simple life with alms taken from folks, at the same time curing their diseases and relieving stress just with plain water. Contrary to my service, what harm did I cause you?  You tortured me with acts of deceit. Have you forgotten the promise given that you would not torture or trouble any Pandaram or Mendicants and in the event the you broke the promise you would meet destruction with your entire family members?  Was it fair to harass me who was in the form of a Pandaram? Did you honor your promise, tell me oh, heinous evil, think whether you had done anything good in any one of the past seven births? If I had to reveal the extent of tortures and troubles faced by me, there would be no space to accommodate them even in all the seven worlds.
<br /><br />
'Oh, sinner, where are your forces, guards, palace, stooges and forces of Elephants? Where have they all gone?  You dug your own grave and met death by your own evil acts. You were responsible for creating your own destiny of destruction. By your heinous and evil act, in every one of your past births, you got killed ignominiously. In every one of your births, I too incarnated in some form to watch your acts and deeds, but you chose to torture and trouble those who chanted my name. You did not even show the least humanity expected and imprisoned and tortured them. That is why in one of your past births I cursed you that you would take birth by your own volition and get destroyed by your own evil acts.   
<br /><br />
'As destined, you were born in the name of Kalian and lived till now and met your end as destined due to your own evil acts. You are going to hell after surrendering the boons which I had bestowed besides surrendering the Chakrayutha (Hand held weapon wheel) given to you’.  Unable to reply to any of the charges leveled against him, Kalian would be sent to hell. After scrutinizing his evil acts, heinous crimes, inhuman acts, forgery, fraudulence and acts of deceit, he would get fair judgement from the Lord. He would be sent to hell and pushed to a place where both ‘fire’ and ‘death causing worms’ will eat him to end his life forever.
<br /><br />
Lord Maha Vishnu would continue to guard the same Universe which he has created.  As and when he decides to build new Dharma Yuga, he would blow a conch, the sound of which would reach all corners of the seven worlds when people with good virtues would begin to take birth followed by appearances of fresh trees, plants, vines, animals, reptiles and all chaste creatures.  Lord Maha Vishnu seated in the lion face studded golden throne embodied with thirty-two holy virtues, guarded on both sides by two golden skinned guards would again incarnate on earth to establish rule of Dharma and ensure people with good virtues to become rulers of the land.
<br /><br />
In the Kali Yuga, Lord Maha Vishnu appeared in the form of Pandara and settled in the southern end in the moth of Maasi in the year Kollam 1008 after taking birth in Tiruchendur. He enacted many divine plays and cured the dreaded diseases of people with simple water. He removed their sins, relieved their sufferings, bestowed several boons   for the welfare of mankind. He burnt the sins of many, married the seven maidens in full purview of the public and appeared in several divine forms to establish that all divines were one and the same. He ensured that the folks worshiped single divine, chanted the only sacred Nama mantra 'Ayya Siva Siva Siva, Siva Arahara Arahara'. With good teaching and preaching, he paved way for the folks to tread the path of Dharma. 
<br /><br />
As per a document available, it is believed that on hearing the news of Lord Vaikundar who was the incarnation of Lord Mahavishnu, Swami Vivekananda while on visit to Kanyakumari in December 1892 CE, went to Swamithoppu in Manavaipathi and   from then on, he reportedly began to wear a turban over his head. The followers of Lord Vaikundar consider the Holy text Akilathirattu Ammanai, as their Veda agama and believe in the principle of one God (Monotheism). Lord Vaikundar is affectionately called by the devotees as ‘AYYA’ because the Lord appeared and stayed with them in the form of a Pandaram (mendicant) in human form. Earlier known as Narayanaswamy Vazhi, it is now called as Ayya Vazhi. The temple of Ayya Vazhi exists in several parts of the world. Ayya Vazhi temple is also locally called as Narayanaswamy Kovil (Temple). His ideals are propagated through Pathis (place of God), which are congregational worship centers to propagate the teachings of Vaikundar.
<br /><br />
The Lord who incarnated in every one of the Yugas is going to destroy Kali yuga to pave way for the dawn of Dharma Yuga to be ruled by him.  Therefore, we too should tread the path of Dharma and walk in the way the Lord Ayya alias Vaikundar showed us to attain success in our life in the Dharma Yug.
<br /><br />
<b><center style="font-size:20px;color:Maroon;">AYYA UNDU</center></b>

</div>
</asp:Content>

