<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="history-of-ayya-vaikundar.aspx.cs" Inherits="history" Title="History of Ayya Vaikundar-English" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>Ayya Vaikundar - History of Ayya Vaikundar</title>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div style="padding:10px;"><h1>History of Ayya Vaikundar</h1></div>
<div class="space"></div>
<div class="right"><a href="history-of-ayya-vaikundar-in-tamil.aspx"> தமிழில் வாசிக்க</a></div>
<div class="space"></div>
<div style="padding:5px;">
<b><center style="font-size:25px;color:Maroon;">AYYA THUNAI</center></b>
<br />
<b><center style="font-size:18px;color:#0000ee;">HISTORY OF LORD NARAYANA’S INCARNATE LORD VAIKUNDAR</center></b><br /><br />

<b>Lord Vaikunda Swamy (C.1833 – C.1851)</b> : Beloved folks, Holy Akilathirattu mentions that ‘Lord Narayana himself incarnated as Lord Vaikundar’.  True to it, Lord Narayana incarnated as Lord Vaikundar not only to uplift the status of the exploited folks of the land who were treated with contempt in the society and left to suffer various hardships, but also to create an egalitarian society amongst the rich and poor without discrimination on caste. His incarnation as Manu (human form) was meant to bring an end to the Kali Yug and usher in the Dharma Yuga.

<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As per Holy Akilathirattu, whenever the forces of Adharma (Evil) raised its ugly head, Lord manifested  in some form or the other as saviour of Dharma. Thus, in Kali Yuga too, when the evil forces threatened to destroy the fabric of Dharma, Lord Narayana incarnated as Lord Vaikundar to uphold rule of Dharma after destroying evil Kali.  Whenever Lord incarnated in some form in Bhoologa, he ensured that the glory and divine plays of such incarnations were made known to the universe in the form of word-of-mouth stories, sacred scriptures or epics etc. To mention few are Ramayana which delineated the eminence of Lord Rama, Mahabharata which portrayed the eminence of Lord Krishna and Skanda Purana which delineated the eminence of Lord Muruga etc.  True to this philosophy, to let the universe know of the incarnation of Lord Vaikundar, a sacred text called Akilathirattu Ammanai has also been written.  
<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; As per Holy Akilathirattu, the Lord who created the cosmic and pervaded everywhere,  incarnated in every one of the Yugas to destroy the evil forces to save the mankind.  Before dawn of Kaliyuga, Lord Narayana incarnated in different forms in Nedu Yuga, Chatur Yuga, Dwapara Yuga, Kretha Yuga and Thretha Yuga, and killed the Asuric forces such as Groni, Singa muga Sooran, Duryodhanan etc.  
<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; According to the Adi Agama composed by Veda Vyasa, Lord Narayana incarnated as Lord Vaikundaswamy on the 20th day of Kollam year 1008 Masi (C.1833) in Kali Yuga in Tiruchendur Tirupattu ocean, as son of his own (Lord Narayana) and Goddess Mahalakshmi who was till then growing in the form of a makara inside the sea in Tiruchendur Tirupattu ocean.  After taking birth inside sea, he got important precepts from Lord Narayana , followed by Goddess Saraswathi rendering beautiful lullabies hailing him. After awakening from divine slumber Lord Vaikundar came out of the sea to enlighten the rishis, munis and devas who were waiting for him. After accepting their salutations, the Lord turned into the form of human (Manu) before finally reaching the seashore where the folks of the lands were waiting. He appeared before them in the form of a mendicant (Pandaram) in the same southern part of India.
<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; In order to end Kali and to get social status to the exploited folks of the land to live on par with folks of higher status in the society, the Lord in the form of mendicant  undertook severe penance for six years praying to Lord Shiva. During such period he  enacted several divine plays and  cured various ailments of the folks by simply giving water and sacred sand. 
<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Attracted by the advocacy of Lord Vaikundar which spread across the land, the folks belonging to eighteen castes who then remained exploited flocked to him in belief that he had incarnated to uphold Dharma as prophesied in the Veda Agamas and to usher in a casteless society soon thereafter.  The rulers of Travancore when realized Lord Vaikundar was drawing  huge forces of folks and a separate socialistic state of society was slowly and steadily emerging in Swamithoppu, ignoring the advice of  saner persons like  Poovandar, the King got the Lord arrested and tortured him variously. He imprisoned,  poisoned, pushed him into the cage of hungry tiger and made him sit in lime kiln poured with water. However, none of the such brutal acts caused any harm to the Lord in human form and therefore the King was forced to release him from the prison. Once released from prison, Lord sent the folks called Sandroars who were born in the lineage of  the sons  of Saptha Mathas to undertake a unique penance called  Thuvayal Thavasu to adapt new chapter in their life style, convert their views into that of high  order and finally mold them to remain disciplined folks in life. After successful completion of the thavasu, Lord sent all of them back to their homes.
<br /><br />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; During his stay in bhoologa Lord Vaikundar enacted several divine plays and  recreated divine marriages in bhoologa with seven divine maidens called Saptha Kannigas namely  Maragatham alias Sasthiratal, Valle, Valli, Saligai, Sarakathakanni, Sarithai and Arimadavami who had all taken birth in human form. While marrying the Goddess Lakshmi, Goddess Bhagavathi (an aspect of Goddess Parvati), Mandaikattal (an aspect of Goddess Saraswathi), Goddess Valli and Goddess Devyani, followed by Poomadanthai (an aspect of Goddess Bhumadevi) - all in human form Lord Vaikundar too converted himself into the form of respective divines who were the husbands of those particular divine maidens. All the marriages with the divine maidens were imaginary marriages enacted to show the folks the marriage of divines in bhoologa.
<br /><br />
 &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Thus, after enacting several such plays for  over 18 years in Kali Yuga, he ended   his incarnation at 12 noon on Monday, the 21st Vaikasi in the year Kollam 1026, (corresponding to 2nd June C.1851) and returned back to Vaikunda. While Veda agama Akilathirattu, reverently mention him (Lord Vaikundar) as Ayya, Vaikunda Swamy, Vaikundar, Vaikundaraja, Shri Pandaram, Aandavar, Mayon, Lord Narayana, Lord Vishnu, Thirumal, Perumal, Ayya Narayana, Siva Narayana and Surya Narayana, the devotees reverently worship him in the names of ‘Ayya’, ’Lord Vaikundar’, ‘Lord Vaikunda Swami’ and ‘Lord Narayana Swami’.  The temples of Lord Vaikunda Swami are known in various names such as ‘Pathi’, ‘Thiru Nizhal Thangal’, ‘Sreeman Narayanaswami Kovil’ and ‘Inai Thangal’. People's celebrate Ayya Vaikunda Swami's birthday as Vaikunda Avatara festival. The followers of Ayya Vaikunda Swamy are known as "Ayya Vazhi". The name earlier called as 'Narayanaswamy Vazhi' is now known as 'Ayya Vazhi'. They are spread not only in the southern states of India, but also spread across the globe. More than 10,000 Ayya Pathis/Temples (Sreeman Narayanaswamy Temples) have been established both  in the southern states of India and across various parts of the world.
<br /><br />
<div class="right"><a href="detail-history-of-ayya-vaikundar.aspx">Read More</a></div>
<b><center>Ayya Undu</center></b>
<br /><br />

<%--<div id="history">
    <div><b>Ayya Vaikundar</b> (Tamil: அய்யா வைகுண்டர்), according to Akilattirattu Ammanai (or Akilam), a scripture of the Ayyavazhi, was a Manu (father, sovereign) avatar of Narayana, incarnated as <b>Muthukutty</b> or <b>Mudisoodum Perumal</b>, a Nadar of Swamithoppe, Tamil Nadu (1810 — 1851). He is referred to as <b>Sampooranathevan</b>, a deva (a deity).
The exact date of birth of Mudisoodum Perumal is unknown. It is mostly placed in either 1810 or 1809. while others follow the view of Akilam.

</div>
<div class="heading">
Birth of body and spirit</div>
<div>In 1809 a child was born to the couple Ponnu Nadar and Veiyelal in south India, at Swamithoppe in the Kanyakumari District(part of Travancore then). They were very poor. They initially named the child <b>Mudisoodum Perumal</b>, meaning "Lord Vishnu with a crown", but due to objections from those of higher castes, the family changed his name to Muthukutty.</div><br/>
<div>The religious book, Akilam, tells of a legend of a child who was born dead, and then the soul of the deva Sampooranathevan was placed in the body. According to the legend, the parents found the child still for a time immediately after birth, then the child began behave normally. Thereafter, that boy grew up called <b>Muthukutty</b> in human history, and Sampooranathevan in Ayyavazhi mythology.</div><br/>
<div>Muthukutty, a religious boy, had special interest in the worship of Vishnu. The holy book Akilam mentions that he had set a pedestal for Lord Vishnu in his house and worshipped the deity devoutly. At the age of seventeen, Muthukutty married Thirumalammal from the nearby village of Puviyur, and started a family with her. However, some believe that they were not married at all, but that, she had come to live with him only to serve him during his public activities.[ Thirumalammal had been previously married, but left her former husband to marry Muthukutty. According to quotes found in Akilam, they had a male child, who was sired by her first husband. Muthukutty earned his living as a Palmyra palm climber and as an agricultural laborer.</div><div class="heading">
The transformation</div>
<div>In his twenty-fourth year, Muthukutty was struck by a severe illness and suffered for a year. His mother took her sick son to the temple at Thiruchendur, during a festival in Thiruchendur. There, Muthukutty went in to the sea and disappeared. The parents searched for his body for a whole day. According to legends, on the third day, Vishnu appeared on the sea-shore. On seeing him, Muthukutty's mother mistook him for her son and tried to embrace him. But the god told her that he was no longer her son, but the son of Narayana. Then he started walking towards Detchanam. This place became a holy place for the devotees of Ayyavazhi and they erected a temple there named Avatharappathi at Thiruchendur. This event is celebrated during the festival of Ayya vaikundar avataram.</div><div class="heading">
The incarnation of Ayya Vaikundar</div>
<div>Ayya Vaikundar, who arose from the sea at Thiruchendur (As per Akilathirattu Ammanai) on 20th of the Tamil Month of Masi, (March 4, 1833 C.E; 3/4/1833) is considered a unique Avatar by the followers of Ayyavazhi. Akilam, speaks about it in great detail, as summarized below:</div><br/>
<div>In each of the five yugas prior to the transformation of Ayya Vaikundar, as each fragment of Kroni (evil or Devil) came into physical form, the Lord Vishnu incarnated as well, destroying them. However, in this the sixth yuga, the evil was called Kali, (not the Hindu deity) and having no physical form he occupied the mind of people of earth as the Mayai (illusion), causing them to behave discourteously. Kaliyan claimed, it was impossible to destroy him in this yuga as in the previous ones as he held the boon from gods, it was impossible for Narayan, or any others, to incarnate in the world to destroy him. Since God could not incarnate directly, He incarnated as Ayya Vaikundar in three stages.<ul>
<li>The first stage of Avatar was the born dead child (birth of the Body).</li>
<li>Next, immediately the soul of Sampooranathevan was installed into the body, along with the Spirit (not Soul) of Narayana kept in Parvatha Ucchi Malai (a mythical mountain believed to be in this region) after the completion of the Krishna Avatar. This was the second stage of the Avatar.</li>
<li>Then in the sea (during the 24th year), the soul of Sampooranathevan was granted moksha (liberation from the cycle of death and birth, synonymous with heaven), unified to the Ultimate Soul. Now, the Spirit of Narayana along with the Ultimate Soul (Paramatma) incarnated in the body of a human being (Muthukutty). This is the third stage of Avatar and from then he was called Ayya Vaikundar. Then Ayya Vaikundar was given Vinchai by Narayanar.</li><ul></div>
<div>According to Akilam Ayya Vaikundar was not merely a human, not merely Narayana, and not merely the Ultimate Soul, but on the other hand he was a human and he was the Ultimate Soul and he was Narayana. He was the one who had the responsibility to destroy the evil of Kali. There is another view that Vaikundar did not take a human body and showed only a bodily appearance to mankind based upon some quotes in akilam.</div>
<div class="heading">Tavam</div>
<div>Having reached Poovantanthoppe, (present-day Swamithope), he undertook to perform a penance. The penance consisted of three stages, each spanning two years. There is a tradition that describes his postures during the six-year tavam as follows: during the first two years, he stood inside a pit of six depth, during the next two years, squatted on the ground, and, during last two years, sat on a raised platform. His appearance was squalid, "long and entangled plait of hair" and frayed clothes. He spoke less and subsisted on frugal meals.</div>
<div class="heading">Incinerating evil spirits</div>
<div>Akilattirattu speaks of this act of incinerating the evil spirits as an important event in the incarnation of Ayya Vaikundar. It took place when he was performing his great penance, which had been announced by him to be the means of destroying the kalimayai - the illusory evil force. He, then, gathered the people around, and caused some of them, both male and female, to get possessed of the evil spirits (peyattam). The possessed ones came and danced in front of the crowd as if the evil spirits had come upon them. Vaikundar, then, ordered these evil spirits to make an oath, in front of the people, to surrender their powers and get burned up in flames. When he had finished his orders, those dancing under the duress of possession got exhausted and fell flat on the ground. Thus the evil spirits were incinerated.</div>
<div class="heading">Seizing the powers of witchcraft, sorcery, and other esoteric magical practices</div>
<div>Similarly, Vaikundar performed another action to 'seize the esoteric evil powers'. Akilam says that, he took away the powers of those who knew to perform witchcraft, sorcery, and other magical rituals. People living in the hills, called as Kanikkarar, were believed to be powerful shamans or witchdoctors, having powers to contain or to provoke the demons. Vaikundar, in a trance, made some of these Kanikkarar to testify in front of the people that they had surrendered their powers. People grew appreciative of Ayya Vaikundar's actions. They began addressing him as Vaikuntacami. This implied an attribution of divinity to Vaikundar. Vaikundar exhorted the people as follows:
<p><i>"There are no demons, no devils, No ill effects of magical practices, No disease, no pain, and no extortion of taxes, And, therefore, live courageously."</i></p></div>
<div class="heading">Vaikundar as Pantaram</div>
 

<div><p>The things used by Ayya Vaikundar; 'Surai Koodu', 'Pirambu' and 'Thandayam'.
The fame of Vaikundar had begun to spread in the countries of Travancore and Tirunelveli, and he had been gradually recognised socially as a religious person with extraordinary powers. In the religious parlance of the time, he was addressed as a Pantaram, a religious person hailing from, and serving the ordinary folk. Akilattirattu addresses him as NarayanaPantaram. </p>
<p>People came to him to listen to his teachings and instructions, to be cured by him of different diseases, to witness, worship and serve a religious person. Vaikundar encouraged the people to come together around a well to take a ritual bath, irrespective of caste differences. He encouraged them to dine together in his presence.</p>
<p>He gave out a number of teachings and instructions, the central point of which was that he had come to abolish Kali Yukam, and to usher in an age of Dharma Yukam, during the time of which the now-oppressed and suffering people would be liberated and rule the land under his leadership. 'Uplift of the lowly is dharmam’ was a constant refrain in his teachings. People were encouraged to serve as catalysts for the destruction of Kali by transforming themselves to be 'people of Dharma Yukam' and to acquire a new character. The new character would come upon them, he said, if they learned to live with self-respect, social dignity and fearlessness. Underscoring the importance of self-respect and social dignity, he said, ‘if one lives with dignity and self-respect, the kali would destroy itself’ . He said when people grew out of kalimayai, Dharma Yukam would unfold itself and in that age, he would rule over the people as Dharma Raja, the king of Dharma Yukam.</p></div>
<div class="heading">Arrest and imprisonment</div>
<div>Against the background of the growing popularity of Vaikundar, and the convergence of people around him in multitudes, a complaint seems to have been lodged against him with the king of Travancore. The king arrested Vaikundar and tortured him. There is an opinion that Ayya Vaikundar was arrested on 11 November 1839. But the date is not mentioned in Akilam.</div>
<div class="heading">Post-imprisonmet activities</div>
<div>After he returned from imprisonment, Vaikundar inspired a group of his devotees to undertake a religious exercise called Thuvayal Thavasu. He also practiced several miracles. He married the Saptha Kanniyar as Narayanar, the Seven deities in the form of Ekam, He initiated a lot of festivities around him." The deities were made to 'come upon' some of the female devotees who became their human media, and then a marriage ceremony was performed with these human media. There were ceremonial processions held amidst singing, incantations and shouts of joy by the followers. Several rites and rituals were instituted during these occasions.</div>
<div class="heading">Attaining Vaikundam</div>
<div><p>Later Vaikundar was invited by his devotees to their homes and treated in a grand manner. By way of soliciting his blessings, his devotees carried him to different places. During these occasions, he laid foundations in various places for small shrine-like centres, called as Nizhal Thangals. Vaikundar came to recognize five individuals as his closest disciples. Through one of his disciples, Hari Gopalan Citar, he wrote the holy book, called Akilam. </p>
<p>On 3 June 1851 Vaikundar attained Vaikundam .However, Samuel Mateer mentions the year as 1848. But today most of the historians opinins it as it is mentioned in Akilam. As he attained Vaikundam his body was interned in a tomb and, around that, a pati (temple) was raised later on. His devotees continued to visit this site, and performed the rituals as they used to do when Vaikundar was bodily present. His life and works remain the foundation of the Ayyavazhi. The head temple of the Ayyavazhi religion is the Swamithoppepathi and is located in the Village of Swamithope.</p></div>
<div class="heading">Five Citars</div>
<div>Ayya Vaikundar has five disciples (citars). According to Akilattirattu Ammanai the Pandavas of previous Dwapara Yukam was made to take birth in this Kali Yukam as Citars of Vaikundar. They are:
<ul><li>Dharma Citar</li>
<li>Bhima Citar</li>
<li>Arjunan Citar</li>
<li>Nakulan Citar</li>
<li>Sakatevan Citar</li></ul></div>--%>


</div>
</div>
</asp:Content>

