<%@ Page Language="C#" MasterPageFile="~/MasterPage.master" AutoEventWireup="true" CodeFile="history-of-ayya-vaikundar.aspx.cs" Inherits="history" Title="History of Ayya Vaikundar-English" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <title>Ayya Vaikundar - History of Ayya Vaikundar</title>

</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div style="padding:10px;"><h1>History of Ayya Vaikundar</h1></div>
<div class="space"></div>
<div class="right"><a href="history-of-ayya-vaikundar-in-tamil.aspx"> தமிழில் வாசிக்க</a></div>
<div class="space"></div>
<div style="padding:10px;">
<b><center style="font-size:25px;">Ayya Thunai</center></b>
<br /><br />
<b>Lord Vaikundar Avatar:</b><br /><br />

Lord Vaikundar (c.1833–c.1851) is 10th avatar of Lord Narayana, also popularly called as “Narayana Pantaram” or “Kalki” alias “Ayya”. Lord's avatar happens to be next to his Krishna avatar. In this avatar, Lord Narayana incarnated as “Trimurti” alias “Siva Narayana”.

Whenever Lord Narayana incarnates, he gives the details in scriptures about his incarnation. The Akilattirattu is the divine scripture, which gives the details of tenth incarnation of Lord Narayana in form of Vaikundar. 
<br /><br />
<b>“This is the story of God’s incarnation in kali yuga - To make and rule the subsequent dharma yuga”</b>
<br /><br />
Akilattirattu gives the world's historical and mythological events. It also gives prophecy of the avatars of Lord Narayana and his coming along with extensive quantity of historical facts. This holy book focus on the “supreme oneness” and narrates the events starting from the creation of the Universe. It also explains us what has happened so far and what is going to happen next. This holy book was compiled by his fifth citar - Hari Gopalan on Kollam Year 1016 at 27th day of Tamil Month Karthikai (10th December 1841 CE, Friday). Hari Goplan received holy Apostle from Lord in his dream, which commissioned him to write the Akilattirattu by giving him the first syllable - “The Kappu”.
<br /><br />
<b>Previous Avatars of God:</b><br /><br /> Akilattirattu says, whenever the yuga ages and major injustice happens, God appears as incarnations to establish dharma by destroying adharma. At the beginning of Universe, devas gathered in Kailasa and had Amrutham. After having, devas asked Lord Shiva, do we have any enemies. To answer this, Lord Siva lits an agni kunda and went himself into it and sang vedakandam with dance. After completion when he returned from agni kunda, a deadly monster called Kroni (Asura or evil force) was also born inside an agni kunda. After few days, the evil force kroni was trying to destroy Kailasa in order to kill devas. To save devas, Lord Narayana took a penance to get grace of Lord Shiva to destroy Kroni. Lord Shiva appeared and said to Narayana, "Kroni should be cut in six pieces”. In doing so, every piece of him will be born as a monster on the earth, and you will have to incarnate to destroy the other demons. Lord Narayana consents and chops Kroni into six pieces in Neetiya yuga. Accordingly, Lord Narayana incarnated by the Yuga-Yugas in order to protect the Dharma. So, he appeared in the Chathur Yuga and the Netu Yuga by destroying the asuras such as Gundomasali, Thillai Mallalan, and Mallossy Vaughan that emerged from Kroni's chunk. Later in the Kretha Yuga, Lord incarnated as Muruga, Narasimha and Sri Rama in the Thretha Yuga to destroy the Asuras such as Singamukha Suran, Surapathman, Iranian, and Ravana. In the Dwapara Yuga Lord incarnated as Sri Krishna to destroy the Asuras such as Duryodhana, Takkan and helped the Pandavas to establish the Dharma by establishing the Pandavas Kingdom again. Kroni was refused to listen Lord Narayana’s council, whenever he was born and destroyed. Lord narayana was angry on this and last said to kroni "You will die because of yourself”. Then, at the end of Dwapara yuga, Lord was known that Kailyan will come, that is the reason he had led the route of forest, while on the way he had taken back the powers of pandavas and left his body on top of the hill and left this world. While on the way to Kailayangiri, Lord saw seven devaloga girls were bathing in the Ganga to prey Lord shiva. Lord decided to test thier worshipness and takes form of fire near Ganga, then devaloga girls rounded the fire flame to feels hotter and forget about worshipping Shiva and gets diverted.This diversion causes all devaloga girls to lose their chastity to Lord and lost thier power. Then, Narayana been to the seven worlds and taken seven seeds and given as kids for devaloga girls. Finally, Lord asked seven girls to take penance, he gives their kids to the Pathirakali to take care and with everyone’s knowledge moved to Srirangam to rest.
<br /><br />
<b>God’s Incarnation in Kaliyuga:</b> By this time by the words of the devas, the Lord Shiva gave birth to the Kaliyan (Asura), that emerged from last and sixth piece of Kroni's chunk. The Kali yuga begun, when the Kaliyan was born. Kroni’s fifth chunk Duryodhana in the previous yuga was transmigrated as Kaliyan in Kali yuga. After his birth, he got lots of boon from Lord Shiva, which had more powers compared to the powers of the Asura of previous yuga’s. His Powers included reign of the King, various tricks, long life tricks and the Lord’s Chakrayuta. When Kaliyan was on the way to earth, Lord Narayana in the form of Pantaram (Monk) stopped him and challenged him for fight. Kaliyan ignored by saying, “I have lot of powers, If I fight with you, my wife will laugh!”. In response, Lord Narayana asked him to promise - "Going forward he won't fight or disrupt any Pantaram”. Kaliyan agreed and gave the promise – “I will never fight or distrupt any Pantaram, If I will do so, will lose everything and will go to hell". Akilattirattu says, this is the reason behind Lord Narayana’s tenth avatar in Kaliyuga as Narayana Pantaram.
<br /><br />
It is said that this Kaliyan became the king of earth in various places and tortured the lives of the good people. He created various caste system in order to divide and rule. Collected heavy taxes from public, That is to say, from feather to Mangalasutra, he put heavy taxes and tortured the people lives. Due to this, Lord Narayana got angry and advised Kaliyan to stop torturing the people who are innocent by mind and heart. However, he did not agree and preferred death rather than giving up. As per the vedas of sage Vyasa, In order to stop the rule of Kaliyan and to bring an end to this Kali yuga, Lord Narayana planned to make Vaikundar incarnate as Pantaram.
<br /><br />
When the day came, In Kali yuga, the Lord Narayana himself incarnated as Vaikundar during an encounter with a deity Goddess Lakshmi, he was beget inside the sea and arose from the sea of Tiruchendur on Kollam Year 1008 at 20th day of Tamil Month Masi (1st March 1833 CE, Friday). He took the human form as Pantaram at Tharuvaiyur near seashore, this is considered a unique avatar. From the point of incarnation of Vaikundar, it is said that he will destroy Kaliyan and the evil in Kali Yuga. It is also said that he will take all righteous people along with him in the succeeding eighth yuga called as Dharma yuga.
<br /><br />
 I (Hari Gopalan) am writing these words of Akilattirattu Ammanai with the grace of God!
“ ‘O’ Lord you took avatar for Pandavas and eliminated their enemies. 
    You attained the abode of Kailasa with anger due to birth of Kaliyan. 
     Came again to the world to protect santror (good people) and dharma” 
<br /><br />
“On Masi 1008, I (Lord Narayana) myself appeared as Pantaram on the banks of sea, have taken residence in Theksanapuri as Vaikundar” – Akilattirattu
<br /><br />
Akilattirattu says, Lord Narayana himself incarnated as Vaikundar and appeared as Pantaram on the banks of sea. This place became a holy place for the devotees of Ayya vazhi and they erected a temple there named Avathara pathi.
<br /><br />
God says this prophecy, 
"I (Lord Narayana) took the avatar for yuga trail and became the praise child for Sita.
 As a king of Dharma yuga, I am going to rule the world with single command" – Akilattirattu
<br /><br />
In the name of Vaikundar, Lord came towards Swamithopu as Pantaram. Lord Vaikundar as a Pantaram, had donned himself in squalid rags, smeared the white mark on forehead, tied a turban on his head and carried a cane. Upon reaching Swamithopu, he undertook a penance for 6 years to get grace and power of Lord Shiva. He got the power to abolish the rule of the evil force Kaliyan from the world and for the subsequent end of Kali yuga. Lord did many mighty miracles. These incude, curing all the diseases for those people who came to get blessing from him. He baught eighteen-caste people together for peace and equality. Lord Vaikundar had five disciples (Citars). According to Akilattirattu, the Pandavas of previous Dwapara yuga were made to take birth in this Kali yuga as Citars of Vaikundar. The holy book Akilattirattu was compiled by his fifth citar - Hari Gopalan alias Sahadeva.
<br /><br />
The grace of Lord Vaikundar spreaded everywhere. People visited and listened to Lord's teachings and instructions. Vaikundar instructed devotees “Dharma Vaikundam, just born now” and guided 14 lokas to follow Dharma. He says - From now on, everyone will dedicate themselves to me and everyone should unite with single thought to live together. Never give offerings in hundi, the man and the woman should get together and pray to me. I am Narayana, creator of the world, fear only for me - no one else. In addition, Lord also instructed dharma for birds, animals and all living things in the world. In those days, lower caste peoples not allowed to wear turban and a dhoti up to the toes. Vaikundar asked all the people who came to him to wear a turban and a dhoti up to the toes. He asked people to come together to take a ritual bath, irrespective of caste, religion, race and creed. He also encouraged them to dine together (Samapanthi-bhojana) in his presence. In order to strip of the evil of untouchability, he applied the scared clay (Thottu Namam) on the forehead of the devotees by touching with fingers. He advised the devotees to use one's own local language to worship God. 
<br /><br />
Lord Vaikundar encouraged all his devotees to do the collective worship. 'Uplifting the poor is Dharma’ was a constant refrain in his teachings. Lord instructed devotees to follow dharma, since dharma bears a great deal. 
<br /><br />
Underscoring the importance of self-respect and social dignity. Lord said, ‘If one lives with dignity and self-respect, the kali would destroy itself’.
<br /><br />
He also said, In the forthcoming Dharma yuga, there will be people ready to give charity but there won't be any takers. If you want to reach the Dharma yuga, you must love all the creatures, which I have created. You must abandon all the superstitions on scarifying animals while worshiping God. People were encouraged to serve as catalysts for the destruction of Kali by transforming themselves to be 'People of Dharma yuga” by loving each other. He advised devotees to live with self-respect, social dignity and fearlessness. Thus, developed equality, social justice, self-respect, fearlessness and charity. This is how the oppressed people were liberated from slavery.
<br /><br />
Upon teachings, blessings, and guidance of Lord Vaikundar all sections of people were benefited. This has caused the eyes of the Kali dominated people. They complained to the king of Travancore that they were worried that a peaceful "dharma empire" was developing in Swamithopu in the name of Vaikundar and people are worshipping him as an avatar of Lord Narayana. 
When the king heard this, he called his astologer to look at shastra. The astrologer said “My dear king, Karma Kali-dosam spreaded all around, and so the Lord is comming to earth and destroys kali with dharma and create peaceful world. Narayana is going to incarnate as human in the name of Vaikundar.This is the day he comes to govern everything by selecing good people and giving them good boons.” 
<br /><br />
 The Kaliyan king Swathi Thirunal said,
“Even if the great Narayana wanted to incarnate, would he be leaving aside the honorable castes, come into this untouchable Chanar people. It looks to be a cheating".
<br /><br />
 Listening to the king, Poovandar, an elderly person from a shepherd caste, who was in the assembly, advised the king saying:
 "If Narayana wants, he will take birth in any race and in any form. He may come as a Panan or a Pariyan. he took avatars in previous six yuga's and made many illustrations. So better not to disturb this person". He may come in any form or caste. He came in the clan of Kusvan, Kuravan, Masvan, Madena, Visuvana, Vedna and more. He will be available everywhere.
<br /><br />
The Kaliyan king Swathi Thirunal was infuriated and was not ready to listen to anyone in counsel. Since he was influenced by the Kali domination, he had imprisoned Vaikundar at Singarathoppu jail in Travancore and practiced evil. The Kaliyan Kaliyan king wanted to test Vaikundar’s powers. Once five kinds of poison were mixed in an arrack and given to him to drink. Vaikundar drank it as if he were drinking milk and remained unaffected. They set a fire on pieces of wood and asked him to walk and remained unaffected. Finally, King ordered Lord to be thrown to a starving tiger. The Starving tiger bowed to the divinity, since tiger knows this is god. He is the God of Creation, Sustaining and Destruction. 
<br /><br />
<b>Vaikundar said 
“I’m Narayana, I am the one who created Ekam, the birds, animals and others. I am the one guru of the Universe and the one who measured the 14 worlds in two steps. I am the Creator, I am omnipresent everywhere, I am the one who is sleeping upon the Sheshanaga in the middle of Milky Ocean. I am the soul of every lifebeing. Even If these guys don't know me, that doesn't mean that the animal dosen’t know me.
</b>
<br /><br />
Upon seeing these miracles, The king and the king's forces, who were watching all these events, felt that he was not a human being, but a perfect god’s incarnation to end this yuga. After 110 days of imprisonment and testifying to the genuineness of Vaikundar, he was released from prison on Kollam Year 1014 at 14th day of Tamil Month Panguni (26th March 1839 CE, Tuesday). Akilattirattu states that Kaliyan boon's will be seized as per his promise, since he had disrupted and tortured the Pantaram. 
<br /><br />
Lord Vaikundar who succeeded all the trials and had a plan to return to Swamithopu, at that time, he thought of the “Panchadevas”, who are known as guardian deities by many names in the world. Immediately, the five gods - Garudan, Similan, Kathikaran, Sippai, Muradan - came to Vaikundar. Vaikundar gave the boons to them and taken along with him.  Since then, they have been called as "Sivayee’s”. Vaikundar Surrounded by the devotees, the Sivayee’s and the disciples, came back to Swamithopu and then instructed devotees of several hundred families to undertake a pennace. Also called Thuvayal Thavasu. As an act of ritual singing, the praises of Narayana. 
<br /><br />
After spiritual awakening, Lord had ordered the disciples and the devotees to preach and carry the message saying 
“I (Lord Narayana) am the one who created the Ekam, I am the Trimurthy, I’m the one who measured the world in two feets, I am the one who has taken ten avatars". Through them, thousands of pathis (temples) had been setup throughout the world. So Lord was happy and became Siva Narayana and united all powers.
<br /><br />
Lord also said the prophecy of his coming again to establish the rule as the everlasting king over the Dharma yuga in the place of Kali yuga. In that time Kroni along with wrongdoing people will be sentenced to hell by a final judgment from the Lion-throne of Dwaraka pathi. Which is the rising mythical landmass, which was sunken at the end of Dwapara yuga by Krishna located southeast of present-day Kanyakumari. Good people will be raised by lord and he will give them good boons. These people are going to live long, under single dhama kingdom with single flag under the rule of Lord as dharmarasa. Having accomplished whatever he intended doing, Vaikundar thought of attaining Vaikundam, i.e., leaving this world and going to the world of Vaikundam. He returned to Vaikundam on Monday, the Kollam Year 1026 at 21st day of Tamil Month Vaikasi (2nd June 1851 CE, Monday)
<br /><br />
Sooner in the end of Kaliyuga to safeguard us, Shiva and Parvathi, Narayana and Lakshmi, Bramha and Saraswati and the devas are going to appear in the earth as per Vedas. Whoever came to this Kaliyuga, as per the assurance gave by the god, the old one is going to be destroyed and good things are going to appear. Lord Narayana going to think the of ways to new yuga which will have new earth, new moon, new sky and new air. The Dwaraka temple is going to reappear again. As per God thought, all the wrongdoing people will die, and good people will re-appear. Lord is going to call the ocean to clean up the earth. After cleaning, the ocean is going to bow before the Lord.
In that time Lord Narayana going to do the final judgement. During final judgement, Lord will be asking Kroni “Hey sinner say your words, seven times I have given chance along with boons to you, to reborn and live in this world”. In this Kaliyuga, I took avatar as Vaikundar and burned all the ghosts, cured the diseases of people with water, I have been very grateful to all, whoever followed the dharma. I have stopped kanikai and bribe. I have given advise by calling everybody in single place. You were in double-mind, instead of beliveing me you had arrested and tortured me. Since I was as Pantaram, I didn’t oppose you.
<br /><br />
Just like Pantaram, I have lived and cured the dieases of people. Why did you came and distrupted me. Also, you gave me the assurance that “whoever come as pantaram, I will not distrupt them, if I will do so, I will lost everthing and go to hell.” Then why do you tortucherd me. Did you honoured, what you said. You have taken seven times birth, have you done any good thing.
<br /><br />
As I said earlier “You will die because of yourself”, I said in previous Dwapara yuga “You will be self-born and self-destructive”. As per my words you born as Kaliyan and lived so long. As per your fate your life is over. Whatever the boons I have given, please return and go to hell. Kaliyan will not have any futher words and has to return all the boons. Once the boon returned, he will be thrown to the hell.
<br /><br />
<b>Lord’s Kingdom in coming Dharmayuga:</b><br /><br />  Narayana is a connoisseur of ideas for the new world, the triumphant Sanghu rhythm is going to spread across the world. The good people and good creatures are going to come. All are going to praise Lord Narayana with love, they will say Dharma Vaikundaswamy came. Good natures, good birds and animals, Vedas, Sastras, goodness of the sea, the Ganga, the kamala bhuvani, dharmam will be bowed to the Lord. Narayana is going to give boons to the good people, whoever is reappeared. Lord is going to bless all the creatures and human being with message saying  “Everyone live in Dharmabhumi as sixteen year young and be united” also going to instruct for birds and animals that, do not be afraid, and all of them are united, and depend on the Dharma. Thus the prophecy was fulfilled, on the lion's throne of the great Dwarka Pathi, without any enemies, Lord vaikundar going to rule the world as per vedas.
<br /><br />
<b>"Our King Vaikundar will come and going to rule the 14 worlds in one umbrella SivaSiva SivaSivaa Arakara Arakara"- Arul Nool</b>
<br /><br />
Today’s world, it is very difficult to grasp the different manifestations of the almighty God. We see pundits discriminate between one God and another. Lord Vaikundar as Siva Nararyana has united all the powers into himself as a supreme god. Since Lord insisted worshiping the one and only God and nothing else and pray in the local language with simple chant 'Ayya Siva-Siva Siva-Siva Aragara Aragara'. That is the reason the Ayya pathi’s are growing across the world to worship god by strictly maintaining the equality without distinction of color, race or caste. There is also a view that Swami Vivekananda too was influenced by Ayya vazhi teachings. When he came to Kanyakumari in December 1892, heard the "Vaikundar" incarnation of Lord Narayana and visited the Swamithope Pathi. He was impressed by the principles behind rituals, such as wearing a head gear during worship in temple, worshipping in one God etc., and started wearing a turban from then on throughout his life.Therefore we walk in the way of the Lord; get success in life and dharma yuga life.
<br /><br />
<b><center>Ayya Undu</center></b>
<br /><br />

<%--<div id="history">
    <div><b>Ayya Vaikundar</b> (Tamil: அய்யா வைகுண்டர்), according to Akilattirattu Ammanai (or Akilam), a scripture of the Ayyavazhi, was a Manu (father, sovereign) avatar of Narayana, incarnated as <b>Muthukutty</b> or <b>Mudisoodum Perumal</b>, a Nadar of Swamithoppe, Tamil Nadu (1810 — 1851). He is referred to as <b>Sampooranathevan</b>, a deva (a deity).
The exact date of birth of Mudisoodum Perumal is unknown. It is mostly placed in either 1810 or 1809. while others follow the view of Akilam.

</div>
<div class="heading">
Birth of body and spirit</div>
<div>In 1809 a child was born to the couple Ponnu Nadar and Veiyelal in south India, at Swamithoppe in the Kanyakumari District(part of Travancore then). They were very poor. They initially named the child <b>Mudisoodum Perumal</b>, meaning "Lord Vishnu with a crown", but due to objections from those of higher castes, the family changed his name to Muthukutty.</div><br/>
<div>The religious book, Akilam, tells of a legend of a child who was born dead, and then the soul of the deva Sampooranathevan was placed in the body. According to the legend, the parents found the child still for a time immediately after birth, then the child began behave normally. Thereafter, that boy grew up called <b>Muthukutty</b> in human history, and Sampooranathevan in Ayyavazhi mythology.</div><br/>
<div>Muthukutty, a religious boy, had special interest in the worship of Vishnu. The holy book Akilam mentions that he had set a pedestal for Lord Vishnu in his house and worshipped the deity devoutly. At the age of seventeen, Muthukutty married Thirumalammal from the nearby village of Puviyur, and started a family with her. However, some believe that they were not married at all, but that, she had come to live with him only to serve him during his public activities.[ Thirumalammal had been previously married, but left her former husband to marry Muthukutty. According to quotes found in Akilam, they had a male child, who was sired by her first husband. Muthukutty earned his living as a Palmyra palm climber and as an agricultural laborer.</div><div class="heading">
The transformation</div>
<div>In his twenty-fourth year, Muthukutty was struck by a severe illness and suffered for a year. His mother took her sick son to the temple at Thiruchendur, during a festival in Thiruchendur. There, Muthukutty went in to the sea and disappeared. The parents searched for his body for a whole day. According to legends, on the third day, Vishnu appeared on the sea-shore. On seeing him, Muthukutty's mother mistook him for her son and tried to embrace him. But the god told her that he was no longer her son, but the son of Narayana. Then he started walking towards Detchanam. This place became a holy place for the devotees of Ayyavazhi and they erected a temple there named Avatharappathi at Thiruchendur. This event is celebrated during the festival of Ayya vaikundar avataram.</div><div class="heading">
The incarnation of Ayya Vaikundar</div>
<div>Ayya Vaikundar, who arose from the sea at Thiruchendur (As per Akilathirattu Ammanai) on 20th of the Tamil Month of Masi, (March 4, 1833 C.E; 3/4/1833) is considered a unique Avatar by the followers of Ayyavazhi. Akilam, speaks about it in great detail, as summarized below:</div><br/>
<div>In each of the five yugas prior to the transformation of Ayya Vaikundar, as each fragment of Kroni (evil or Devil) came into physical form, the Lord Vishnu incarnated as well, destroying them. However, in this the sixth yuga, the evil was called Kali, (not the Hindu deity) and having no physical form he occupied the mind of people of earth as the Mayai (illusion), causing them to behave discourteously. Kaliyan claimed, it was impossible to destroy him in this yuga as in the previous ones as he held the boon from gods, it was impossible for Narayan, or any others, to incarnate in the world to destroy him. Since God could not incarnate directly, He incarnated as Ayya Vaikundar in three stages.<ul>
<li>The first stage of Avatar was the born dead child (birth of the Body).</li>
<li>Next, immediately the soul of Sampooranathevan was installed into the body, along with the Spirit (not Soul) of Narayana kept in Parvatha Ucchi Malai (a mythical mountain believed to be in this region) after the completion of the Krishna Avatar. This was the second stage of the Avatar.</li>
<li>Then in the sea (during the 24th year), the soul of Sampooranathevan was granted moksha (liberation from the cycle of death and birth, synonymous with heaven), unified to the Ultimate Soul. Now, the Spirit of Narayana along with the Ultimate Soul (Paramatma) incarnated in the body of a human being (Muthukutty). This is the third stage of Avatar and from then he was called Ayya Vaikundar. Then Ayya Vaikundar was given Vinchai by Narayanar.</li><ul></div>
<div>According to Akilam Ayya Vaikundar was not merely a human, not merely Narayana, and not merely the Ultimate Soul, but on the other hand he was a human and he was the Ultimate Soul and he was Narayana. He was the one who had the responsibility to destroy the evil of Kali. There is another view that Vaikundar did not take a human body and showed only a bodily appearance to mankind based upon some quotes in akilam.</div>
<div class="heading">Tavam</div>
<div>Having reached Poovantanthoppe, (present-day Swamithope), he undertook to perform a penance. The penance consisted of three stages, each spanning two years. There is a tradition that describes his postures during the six-year tavam as follows: during the first two years, he stood inside a pit of six depth, during the next two years, squatted on the ground, and, during last two years, sat on a raised platform. His appearance was squalid, "long and entangled plait of hair" and frayed clothes. He spoke less and subsisted on frugal meals.</div>
<div class="heading">Incinerating evil spirits</div>
<div>Akilattirattu speaks of this act of incinerating the evil spirits as an important event in the incarnation of Ayya Vaikundar. It took place when he was performing his great penance, which had been announced by him to be the means of destroying the kalimayai - the illusory evil force. He, then, gathered the people around, and caused some of them, both male and female, to get possessed of the evil spirits (peyattam). The possessed ones came and danced in front of the crowd as if the evil spirits had come upon them. Vaikundar, then, ordered these evil spirits to make an oath, in front of the people, to surrender their powers and get burned up in flames. When he had finished his orders, those dancing under the duress of possession got exhausted and fell flat on the ground. Thus the evil spirits were incinerated.</div>
<div class="heading">Seizing the powers of witchcraft, sorcery, and other esoteric magical practices</div>
<div>Similarly, Vaikundar performed another action to 'seize the esoteric evil powers'. Akilam says that, he took away the powers of those who knew to perform witchcraft, sorcery, and other magical rituals. People living in the hills, called as Kanikkarar, were believed to be powerful shamans or witchdoctors, having powers to contain or to provoke the demons. Vaikundar, in a trance, made some of these Kanikkarar to testify in front of the people that they had surrendered their powers. People grew appreciative of Ayya Vaikundar's actions. They began addressing him as Vaikuntacami. This implied an attribution of divinity to Vaikundar. Vaikundar exhorted the people as follows:
<p><i>"There are no demons, no devils, No ill effects of magical practices, No disease, no pain, and no extortion of taxes, And, therefore, live courageously."</i></p></div>
<div class="heading">Vaikundar as Pantaram</div>
 

<div><p>The things used by Ayya Vaikundar; 'Surai Koodu', 'Pirambu' and 'Thandayam'.
The fame of Vaikundar had begun to spread in the countries of Travancore and Tirunelveli, and he had been gradually recognised socially as a religious person with extraordinary powers. In the religious parlance of the time, he was addressed as a Pantaram, a religious person hailing from, and serving the ordinary folk. Akilattirattu addresses him as NarayanaPantaram. </p>
<p>People came to him to listen to his teachings and instructions, to be cured by him of different diseases, to witness, worship and serve a religious person. Vaikundar encouraged the people to come together around a well to take a ritual bath, irrespective of caste differences. He encouraged them to dine together in his presence.</p>
<p>He gave out a number of teachings and instructions, the central point of which was that he had come to abolish Kali Yukam, and to usher in an age of Dharma Yukam, during the time of which the now-oppressed and suffering people would be liberated and rule the land under his leadership. 'Uplift of the lowly is dharmam’ was a constant refrain in his teachings. People were encouraged to serve as catalysts for the destruction of Kali by transforming themselves to be 'people of Dharma Yukam' and to acquire a new character. The new character would come upon them, he said, if they learned to live with self-respect, social dignity and fearlessness. Underscoring the importance of self-respect and social dignity, he said, ‘if one lives with dignity and self-respect, the kali would destroy itself’ . He said when people grew out of kalimayai, Dharma Yukam would unfold itself and in that age, he would rule over the people as Dharma Raja, the king of Dharma Yukam.</p></div>
<div class="heading">Arrest and imprisonment</div>
<div>Against the background of the growing popularity of Vaikundar, and the convergence of people around him in multitudes, a complaint seems to have been lodged against him with the king of Travancore. The king arrested Vaikundar and tortured him. There is an opinion that Ayya Vaikundar was arrested on 11 November 1839. But the date is not mentioned in Akilam.</div>
<div class="heading">Post-imprisonmet activities</div>
<div>After he returned from imprisonment, Vaikundar inspired a group of his devotees to undertake a religious exercise called Thuvayal Thavasu. He also practiced several miracles. He married the Saptha Kanniyar as Narayanar, the Seven deities in the form of Ekam, He initiated a lot of festivities around him." The deities were made to 'come upon' some of the female devotees who became their human media, and then a marriage ceremony was performed with these human media. There were ceremonial processions held amidst singing, incantations and shouts of joy by the followers. Several rites and rituals were instituted during these occasions.</div>
<div class="heading">Attaining Vaikundam</div>
<div><p>Later Vaikundar was invited by his devotees to their homes and treated in a grand manner. By way of soliciting his blessings, his devotees carried him to different places. During these occasions, he laid foundations in various places for small shrine-like centres, called as Nizhal Thangals. Vaikundar came to recognize five individuals as his closest disciples. Through one of his disciples, Hari Gopalan Citar, he wrote the holy book, called Akilam. </p>
<p>On 3 June 1851 Vaikundar attained Vaikundam .However, Samuel Mateer mentions the year as 1848. But today most of the historians opinins it as it is mentioned in Akilam. As he attained Vaikundam his body was interned in a tomb and, around that, a pati (temple) was raised later on. His devotees continued to visit this site, and performed the rituals as they used to do when Vaikundar was bodily present. His life and works remain the foundation of the Ayyavazhi. The head temple of the Ayyavazhi religion is the Swamithoppepathi and is located in the Village of Swamithope.</p></div>
<div class="heading">Five Citars</div>
<div>Ayya Vaikundar has five disciples (citars). According to Akilattirattu Ammanai the Pandavas of previous Dwapara Yukam was made to take birth in this Kali Yukam as Citars of Vaikundar. They are:
<ul><li>Dharma Citar</li>
<li>Bhima Citar</li>
<li>Arjunan Citar</li>
<li>Nakulan Citar</li>
<li>Sakatevan Citar</li></ul></div>--%>


</div>
</div>
</asp:Content>

